eto0:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1950_1960/
  climatology: True
eto1:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1960_1970
  climatology: True
eto2:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1970_1980
  climatology: True
eto3:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1980_1990
  climatology: True
eto4:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/1990_2000
  climatology: True
eto5:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2000_2010
  climatology: True
eto6:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2010_2020
  climatology: True
eto7:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2020_2030
  climatology: True
eto8:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2030_2040
  climatology: True
eto9:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2040_2050
  climatology: True
eto10:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2050_2060
  climatology: True
eto11:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2060_2070
  climatology: True
eto12:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2070_2080
  climatology: True
eto13:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2080_2090
  climatology: True
eto14:
  name_fmt: ETo_DOY{}.tif
  dt_fmt: doy
  dir_loc: dev-et-data/in/DelawareRiverBasin/ETo_Moving_Average_byDOY/2090_2100
  climatology: True