publish:
	git config --global user.email tonybutzer@gmail.com
	git config --global user.name tonybutzer
	git config --global push.default simple
	(cd .. ; git add .)
	(cd .. ; git commit -m "automatic git update from Makefile")
	(cd .. ; git push)
