ndvi0:
  name_fmt: FS_1950_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_1950
  climatology: True
ndvi1:
  name_fmt: FS_1960_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_1960
  climatology: True
ndvi2:
  name_fmt: FS_1970_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_1970
  climatology: True
ndvi3:
  name_fmt: FS_1980_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_1980
  climatology: True
ndvi4:
  name_fmt: FS_1990_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_1990
  climatology: True
ndvi5:
  name_fmt: FS_2000_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2000
  climatology: True
ndvi6:
  name_fmt: FS_2010_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2010
  climatology: True
ndvi7:
  name_fmt: FS_2030_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2030
  climatology: True
ndvi8:
  name_fmt: FS_2040_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2040
  climatology: True
ndvi9:
  name_fmt: FS_2050_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2050
  climatology: True
ndvi10:
  name_fmt: FS_2060_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2060
  climatology: True
ndvi11:
  name_fmt: FS_2070_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2070
  climatology: True
ndvi12:
  name_fmt: FS_2080_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2080
  climatology: True
ndvi13:
  name_fmt: FS_2090_NDVI_med_{}.tiff
  dt_fmt: doy
  dir_loc: Z:\Projects\Cloud_Veg_ET\Data\NDVI\delaware_basin_FS_2090
  climatology: True